backend:
  image: imalka13/dockerized-full-stack-app
  tag: latest
  replicas: 1

frontend:
  image: imalka13/dockerized-full-stack-app-frontend
  tag: latest
  replicas: 1

mysql:
  host: db
  user: root
  database: devops_app
  port: 3306

ingress:
  host: staging.myapp.local