name: Auto Deploy to Kubernetes

on:
  push:
    branches: [ "main" ]

jobs:
  deploy-staging:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set image tag
        shell: powershell
        run: |
          $shortSha = "${env:GITHUB_SHA}".Substring(0,7)
          "TAG=$shortSha" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

      - name: Docker login
        shell: powershell
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push backend image
        shell: powershell
        run: |
          docker build -t imalka13/dockerized-full-stack-app:latest ./backend
          docker build -t imalka13/dockerized-full-stack-app:$env:TAG ./backend
          docker push imalka13/dockerized-full-stack-app:latest
          docker push imalka13/dockerized-full-stack-app:$env:TAG

      - name: Build and push frontend image
        shell: powershell
        run: |
          docker build -t imalka13/dockerized-full-stack-app-frontend:latest ./frontend
          docker build -t imalka13/dockerized-full-stack-app-frontend:$env:TAG ./frontend
          docker push imalka13/dockerized-full-stack-app-frontend:latest
          docker push imalka13/dockerized-full-stack-app-frontend:$env:TAG

      - name: Deploy staging with Helm
        shell: powershell
        run: |
          helm upgrade --install fullstack-staging .\helm\fullstack-app `
            -n staging `
            -f .\helm\fullstack-app\values-staging.yaml `
            --set backend.tag=$env:TAG `
            --set frontend.tag=$env:TAG

      - name: Wait for staging rollout
        shell: powershell
        run: |
          kubectl rollout status deployment/backend-deployment -n staging
          kubectl rollout status deployment/frontend-deployment -n staging

  deploy-production:
    needs: deploy-staging
    runs-on: self-hosted
    environment:
      name: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set image tag
        shell: powershell
        run: |
          $shortSha = "${env:GITHUB_SHA}".Substring(0,7)
          "TAG=$shortSha" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

      - name: Deploy production with Helm
        shell: powershell
        run: |
          helm upgrade --install fullstack .\helm\fullstack-app `
            -n default `
            -f .\helm\fullstack-app\values-production.yaml `
            --set backend.tag=$env:TAG `
            --set frontend.tag=$env:TAG

      - name: Wait for production rollout
        shell: powershell
        run: |
          kubectl rollout status deployment/backend-deployment -n default
          kubectl rollout status deployment/frontend-deployment -n default