name: Auto Deploy to Kubernetes

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set image tag
        shell: powershell
        run: |
          $shortSha = "${env:GITHUB_SHA}".Substring(0,7)
          "TAG=$shortSha" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

      - name: Docker login
        shell: powershell
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push backend image
        shell: powershell
        run: |
          docker build -t imalka13/dockerized-full-stack-app:latest ./backend
          docker build -t imalka13/dockerized-full-stack-app:$env:TAG ./backend
          docker push imalka13/dockerized-full-stack-app:latest
          docker push imalka13/dockerized-full-stack-app:$env:TAG

      - name: Build and push frontend image
        shell: powershell
        run: |
          docker build -t imalka13/dockerized-full-stack-app-frontend:latest ./frontend
          docker build -t imalka13/dockerized-full-stack-app-frontend:$env:TAG ./frontend
          docker push imalka13/dockerized-full-stack-app-frontend:latest
          docker push imalka13/dockerized-full-stack-app-frontend:$env:TAG

      - name: Deploy new version
        shell: powershell
        run: |
          kubectl set image deployment/backend-deployment backend=imalka13/dockerized-full-stack-app:$env:TAG
          kubectl set image deployment/frontend-deployment frontend=imalka13/dockerized-full-stack-app-frontend:$env:TAG

          kubectl set image deployment/backend-deployment backend=imalka13/dockerized-full-stack-app:$env:TAG -n staging
          kubectl set image deployment/frontend-deployment frontend=imalka13/dockerized-full-stack-app-frontend:$env:TAG -n staging

      - name: Wait for rollout
        shell: powershell
        run: |
          kubectl rollout status deployment/backend-deployment
          kubectl rollout status deployment/frontend-deployment

          kubectl rollout status deployment/backend-deployment -n staging
          kubectl rollout status deployment/frontend-deployment -n staging